### ISSUE TITLE
i writen a demo, but got a bug

### ISSUE THREAD

**Issue by zhangdekui** [tegaki/tegaki#20]
```python
import json
from typing import List

from tegaki.character import Writing
from tegaki.recognizer import Recognizer


def get_recognizer(i: int) -> Recognizer:
    all_models = Recognizer.get_all_available_models()
    print("all_models ==> ", all_models)
    r_name, model_name, meta = all_models[i]
    klass = Recognizer.get_available_recognizers()[r_name]
    _recognizer = klass()
    _recognizer.set_model(meta["name"])
    return _recognizer


def find(_recognizer: Recognizer, _writing: Writing) -> [str]:
    if _writing.get_n_strokes() > 0:
        candidates = _recognizer.recognize(_writing, n=9)
        candidates = [char for char, prob in candidates]
        return candidates
    return []


def get_test_strokes() -> List[List[List[int]]]:
    with open("./test_strokes.json", "r", encoding="utf8") as f:
        data = json.load(f)
        return [[[p["x"], p["y"], p["timestamp"]] for p in s["points"]] for s in data["writing"]["strokes"]]


if __name__ == '__main__':
    recognizer = get_recognizer(0)
    # todo 获取writing
    writing = Writing()
    test_strokes = get_test_strokes()
    # print("test_strokes ===> ", test_strokes)
    writing.rebuild_strokes_from_json(test_strokes)

    results = find(recognizer, writing)
    print("results ===> ", results)


```

==============================================
i got a bug:
```python
Traceback (most recent call last):
  File "test_code.py", line 39, in <module>
    results = find(recognizer, writing)
  File "test_code.py", line 19, in find
    candidates = _recognizer.recognize(_writing, n=9)
  File "/usr/local/lib/python3.7/site-packages/tegaki/recognizer.py", line 253, in recognize
    results = self._recognize(writing, n)
  File "/usr/local/share/tegaki/engines/tegakiwagomu.py", line 240, in _recognize
    ch = wagomu.Character(nvectors, n_strokes)
  File "/usr/local/lib/python3.7/site-packages/wagomu.py", line 69, in __init__
    _wagomu.Character_swiginit(self, _wagomu.new_Character(n_vectors, n_strokes))
TypeError: in method 'new_Character', argument 1 of type 'unsigned int'
```

**Comment by zhangdekui** [comment]
i solved it.  it works.
========================
```python
# i runned in docker: rackspacedot/python37:latest
# reason: n_vectors type is float, expected int.  
# modifiy this file  /usr/local/lib/python3.7/site-packages/wagomu.py:  
# L69 to:  _wagomu.Character_swiginit(self, _wagomu.new_Character(int(n_vectors), n_strokes))
```

**Comment by zhangdekui** [comment]
thank this great project ✿✿ヽ(°▽°)ノ✿
